### ISSUE TITLE
Setup local WebServer Error.

### ISSUE THREAD

**Issue by polariszz** [75team/gitpress#4]
### 出错信息

```
Opensource polaris$ ./node_modules/.bin/gitpress polariszz/blog
link tplFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/index_error.html
link tplFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/index_default.html
link tplFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/index_slate.html
link tplFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/index_tactile.html
link tplFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/index_phase.html
link tplFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/index_pithiness.html
link tplFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/index_greyshade.html
link widgetFile:/Users/polaris/Opensource/node_modules/gitpress/bin/../app/Tpl/Home/widgets
Error: ENOENT, no such file or directory '/Users/polaris/Opensource/node_modules/gitpress/app/Runtime/Data/app.pid'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at Object.module.exports.log_process_pid (/Users/polaris/Opensource/node_modules/gitpress/node_modules/thinkjs/lib/Lib/Core/Think.class.js:103:16)
    at Object.module.exports.start (/Users/polaris/Opensource/node_modules/gitpress/node_modules/thinkjs/lib/Lib/Core/Think.class.js:16:14)
    at Object.<anonymous> (/Users/polaris/Opensource/node_modules/gitpress/node_modules/thinkjs/lib/Common/runtime.js:103:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
### 系统信息
- 系统： Mac OS X 10.9

**Comment by polariszz** [comment]
Solved by 

```
 makedir -p $GITPRESSPATH/app/Runtime/Data
```

看上去是thinkjs在写pid时没有检查文件夹是否存在。

thinkjs_path/Lib/Core/Think.class.js 103行

```
fs.writeFileSync(pidFile, process.pid);
```

前应该加段小逻辑。
哈哈这个issue应该报告给thinkjs.
