### ISSUE TITLE
运行gitpress出错，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [75team/gitpress#6]
hi.
as3:~# npm install gitpress -g
as3:~# /root/npm/bin/gitpress -h
Error: ENOENT, no such file or directory '/root/npm/lib/node_modules/gitpress/app/Runtime/Data/app.pid'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at Object.module.exports.log_process_pid (/root/npm/lib/node_modules/gitpress/node_modules/thinkjs/lib/Lib/Core/Think.class.js:103:16)
    at Object.module.exports.start (/root/npm/lib/node_modules/gitpress/node_modules/thinkjs/lib/Lib/Core/Think.class.js:16:14)
    at Object.<anonymous> (/root/npm/lib/node_modules/gitpress/node_modules/thinkjs/lib/Common/runtime.js:103:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
as3:~#

**Comment by akira-cn** [comment]
这个可能是权限的问题，sudo一下试试
